//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matura_Zadatak_B20.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajKursNaDan", ReplyAction="*")]
        Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanResponse ProcitajKursNaDan(Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpisiKursNaDan", ReplyAction="*")]
        Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanResponse UpisiKursNaDan(Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequest request);
        
        // CODEGEN: Generating message contract since element name ProcitajSveValuteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajSveValute", ReplyAction="*")]
        Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteResponse ProcitajSveValute(Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequestBody Body;
        
        public ProcitajKursNaDanRequest() {
        }
        
        public ProcitajKursNaDanRequest(Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        public ProcitajKursNaDanRequestBody() {
        }
        
        public ProcitajKursNaDanRequestBody(System.DateTime Datum, string valuta) {
            this.Datum = Datum;
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanResponseBody Body;
        
        public ProcitajKursNaDanResponse() {
        }
        
        public ProcitajKursNaDanResponse(Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ProcitajKursNaDanResult;
        
        public ProcitajKursNaDanResponseBody() {
        }
        
        public ProcitajKursNaDanResponseBody(double ProcitajKursNaDanResult) {
            this.ProcitajKursNaDanResult = ProcitajKursNaDanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequestBody Body;
        
        public UpisiKursNaDanRequest() {
        }
        
        public UpisiKursNaDanRequest(Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Kurs;
        
        public UpisiKursNaDanRequestBody() {
        }
        
        public UpisiKursNaDanRequestBody(System.DateTime Datum, string valuta, double Kurs) {
            this.Datum = Datum;
            this.valuta = valuta;
            this.Kurs = Kurs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanResponseBody Body;
        
        public UpisiKursNaDanResponse() {
        }
        
        public UpisiKursNaDanResponse(Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpisiKursNaDanResult;
        
        public UpisiKursNaDanResponseBody() {
        }
        
        public UpisiKursNaDanResponseBody(bool UpisiKursNaDanResult) {
            this.UpisiKursNaDanResult = UpisiKursNaDanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValute", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequestBody Body;
        
        public ProcitajSveValuteRequest() {
        }
        
        public ProcitajSveValuteRequest(Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProcitajSveValuteRequestBody {
        
        public ProcitajSveValuteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteResponseBody Body;
        
        public ProcitajSveValuteResponse() {
        }
        
        public ProcitajSveValuteResponse(Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajSveValuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Matura_Zadatak_B20.ServiceReference1.ArrayOfString ProcitajSveValuteResult;
        
        public ProcitajSveValuteResponseBody() {
        }
        
        public ProcitajSveValuteResponseBody(Matura_Zadatak_B20.ServiceReference1.ArrayOfString ProcitajSveValuteResult) {
            this.ProcitajSveValuteResult = ProcitajSveValuteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Matura_Zadatak_B20.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Matura_Zadatak_B20.ServiceReference1.ServiceSoap>, Matura_Zadatak_B20.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanResponse Matura_Zadatak_B20.ServiceReference1.ServiceSoap.ProcitajKursNaDan(Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequest request) {
            return base.Channel.ProcitajKursNaDan(request);
        }
        
        public double ProcitajKursNaDan(System.DateTime Datum, string valuta) {
            Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequest inValue = new Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequest();
            inValue.Body = new Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            Matura_Zadatak_B20.ServiceReference1.ProcitajKursNaDanResponse retVal = ((Matura_Zadatak_B20.ServiceReference1.ServiceSoap)(this)).ProcitajKursNaDan(inValue);
            return retVal.Body.ProcitajKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanResponse Matura_Zadatak_B20.ServiceReference1.ServiceSoap.UpisiKursNaDan(Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequest request) {
            return base.Channel.UpisiKursNaDan(request);
        }
        
        public bool UpisiKursNaDan(System.DateTime Datum, string valuta, double Kurs) {
            Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequest inValue = new Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequest();
            inValue.Body = new Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            inValue.Body.Kurs = Kurs;
            Matura_Zadatak_B20.ServiceReference1.UpisiKursNaDanResponse retVal = ((Matura_Zadatak_B20.ServiceReference1.ServiceSoap)(this)).UpisiKursNaDan(inValue);
            return retVal.Body.UpisiKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteResponse Matura_Zadatak_B20.ServiceReference1.ServiceSoap.ProcitajSveValute(Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequest request) {
            return base.Channel.ProcitajSveValute(request);
        }
        
        public Matura_Zadatak_B20.ServiceReference1.ArrayOfString ProcitajSveValute() {
            Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequest inValue = new Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequest();
            inValue.Body = new Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteRequestBody();
            Matura_Zadatak_B20.ServiceReference1.ProcitajSveValuteResponse retVal = ((Matura_Zadatak_B20.ServiceReference1.ServiceSoap)(this)).ProcitajSveValute(inValue);
            return retVal.Body.ProcitajSveValuteResult;
        }
    }
}
